export const SET_GIFT = 'SET_GIFT';
export const SET_GIFTS = 'SET_GIFTS';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const SET_SEARCH_GIFT_PARAMS = 'SET_SEARCH_GIFT_PARAMS';
export const SET_RANDOM_GIFT = 'SET_RANDOM_GIFT';
